name: memo
description: "Joc per treballar la mem√≤ria implementat en Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  arkit_plugin: ^1.2.1
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  arcore_flutter_plugin: ^0.1.0
  provider: ^6.1.5+1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  firebase_storage: ^13.0.4
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  file_picker: ^10.3.8
  google_mobile_ads: ^7.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/brain.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/